### ISSUE TITLE
Problems after installation

### ISSUE THREAD

**Issue by jowasp** [nikolamilosevic86/owasp-seraphimdroid#33]
![image-8](https://cloud.githubusercontent.com/assets/6704344/13867292/ebed335e-ec93-11e5-880d-a3d60bf41792.jpg)
I received an error 'unfortunately seraphim has stopped' after attempting installing on a Blu phone
Android version: 4.2.2
Kernel version 3.4.5
Sent the report logs also
![image-7](https://cloud.githubusercontent.com/assets/6704344/13867282/d6ca63ac-ec93-11e5-93c9-6d8b556cfba8.jpg)

**Comment by jowasp** [comment]
I tried install and uninstall but did get same results

**Comment by nikolamilosevic86** [comment]
Thank you for reporting. Crash report said the following:

''''
java.lang.RuntimeException: Unable to start receiver org.owasp.seraphimdroid.receiver.SettingsCheckAlarmReceiver: java.lang.SecurityException: Requires VIBRATE permission
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2557)
	at android.app.ActivityThread.access$1500(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: Requires VIBRATE permission
	at android.os.Parcel.readException(Parcel.java:1425)
	at android.os.Parcel.readException(Parcel.java:1379)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:228)
	at android.app.NotificationManager.notify(NotificationManager.java:132)
	at android.app.NotificationManager.notify(NotificationManager.java:108)
	at org.owasp.seraphimdroid.receiver.SettingsCheckAlarmReceiver.fireNotification(SettingsCheckAlarmReceiver.java:64)
	at org.owasp.seraphimdroid.receiver.SettingsCheckAlarmReceiver.runCheck(SettingsCheckAlarmReceiver.java:39)
	at org.owasp.seraphimdroid.receiver.SettingsCheckAlarmReceiver.onReceive(SettingsCheckAlarmReceiver.java:23)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2550)
	... 10 more
'''

Which apparently is some bug of Android 4.2, however, there is workaround to which code should be changed http://stackoverflow.com/questions/13602190/java-lang-securityexception-requires-vibrate-permission-on-jelly-bean-4-2

**Comment by thewayofknowing** [comment]
@nikolamilosevic86 It required a minor change, I've pushed it directly to master so the latest apk can be published.

**Comment by nikolamilosevic86** [comment]
@thewayofknowing I guess there was a bit of confusion, since there are updates in gsoc branch and that was the one I was using as main branch. I have merged them, can you check whether everything is ok? 

I probably can publish a version tonight if everything is ok.

**Comment by nikolamilosevic86** [comment]
@jowasp I have updated version on Google Play, it should be available around tomorrow. I don't have physical device with Android 4.2. Would you mind to try to install it again and tell us whether @thewayofknowing fix worked?

**Comment by jowasp** [comment]
Yes, it works now! thx!
