### ISSUE TITLE
SQLite error causing a crash at launch

### ISSUE THREAD

**Issue by bohrium272** [nikolamilosevic86/owasp-seraphimdroid#39]
I managed to fix the package path problem I mentioned in issue #32 . After making a few more changes, the app compiled fine however, immediately on launch, it crashed.

```
03-27 00:19:21.001 26346-26346/? I/art: Late-enabling -Xcheck:jni
03-27 00:19:21.034 26346-26346/org.owasp.seraphimdroid W/System: ClassLoader referenced unknown path: /data/app/org.owasp.seraphimdroid-2/lib/arm64
03-27 00:19:21.084 26346-26346/org.owasp.seraphimdroid E/SQLiteLog: (1) near ".": syntax error
03-27 00:19:21.091 26346-26346/org.owasp.seraphimdroid D/AndroidRuntime: Shutting down VM
03-27 00:19:21.091 26346-26346/org.owasp.seraphimdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.owasp.seraphimdroid, PID: 26346
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{org.owasp.seraphimdroid/org.owasp.seraphimdroid.PasswordActivity}: android.database.sqlite.SQLiteException: near ".": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS org.owasp.seraphimdroid.services (_id INTEGER primary key autoincrement, service_name TEXT)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: android.database.sqlite.SQLiteException: near ".": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS org.owasp.seraphimdroid.services (_id INTEGER primary key autoincrement, service_name TEXT)
                                                                             at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                             at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                             at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                             at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                             at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                             at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                             at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
                                                                             at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                                             at org.owasp.seraphimdroid.database.DatabaseHelper.onCreate(DatabaseHelper.java:50)
                                                                             at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                             at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
                                                                             at org.owasp.seraphimdroid.PasswordActivity.isPasswordCreated(PasswordActivity.java:407)
                                                                             at org.owasp.seraphimdroid.PasswordActivity.onCreate(PasswordActivity.java:127)
                                                                             at android.app.Activity.performCreate(Activity.java:6251)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
03-27 00:19:22.594 26346-26346/? I/Process: Sending signal. PID: 26346 SIG: 9

```

Traced it back to `DatabaseHelper.java` line 50.

**Comment by thewayofknowing** [comment]
I think you've probably done a replace-all for package names. Which is why the table name got changed (it was originally "services" but in your crash log, it has changed to a package name). And you can check [here](http://stackoverflow.com/questions/3694276/what-are-valid-table-names-in-sqlite) that it is not a valid sqlite table name. 
Hope this helps

**Comment by bohrium272** [comment]
It worked. Thanks!! So now that I have solved the package path problem should I generate a Pull Request ?

**Comment by nikolamilosevic86** [comment]
Yes you should if you have not and if it fixes some issue.When it is done, issue should be closed
